<?php
/**
 * One-time helper: downloads the Google Fonts the invitation uses (Pinyon Script,
 * Cinzel, Montserrat, Amiri) and writes cloudflare/fonts/ — the .woff2 files plus a
 * fonts.css that points at them. The build then serves the fonts from the same
 * place as the page instead of from Google's servers (one less connection to open
 * and nothing to wait for). All four fonts are open source (SIL OFL), so
 * hosting them is allowed.
 *
 *   php cloudflare/fonts.php
 *
 * Only needs re-running if the fonts used by ArifAmira/includes/header.php change.
 * cloudflare/fonts/ is committed, so normal builds need no internet.
 */

$repo = dirname(__DIR__);
$dir  = __DIR__ . '/fonts';

function fail(string $message): never { fwrite(STDERR, "FONTS FAILED: $message\n"); exit(1); }

/** Downloads a URL; uses PHP's curl, falling back to the curl program. */
function fetch(string $url, bool $browser = false): string {
    $agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_FOLLOWLOCATION => true, CURLOPT_TIMEOUT => 30,
            CURLOPT_USERAGENT => $browser ? $agent : 'curl']);
        $body = curl_exec($ch);
        if (is_string($body) && curl_getinfo($ch, CURLINFO_HTTP_CODE) === 200) return $body;
    }
    $cmd = 'curl -sSfL ' . ($browser ? '-A ' . escapeshellarg($agent) . ' ' : '') . escapeshellarg($url);
    $body = shell_exec($cmd);
    return is_string($body) ? $body : '';
}

// the exact font requests the page makes today
$header = file_get_contents("$repo/ArifAmira/includes/header.php");
if (!preg_match("#\\\$fontsUrl = '([^']+)'#", $header, $m)) fail('could not find the fonts URL in header.php');
$stylesheets = [html_entity_decode($m[1])];
$config = require "$repo/ArifAmira/config/config.php";
$stylesheets[] = 'https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&display=swap&text=' . rawurlencode($config['greeting_arabic']);

// the character sets worth keeping (Malay needs only latin; latin-ext covers accented names)
$keepSubsets = ['latin', 'latin-ext'];

if (!is_dir($dir)) mkdir($dir, 0777, true);
foreach (glob("$dir/*") as $old) if (is_file($old)) unlink($old);

$css = "/* Self-hosted copies of the Google Fonts the invitation uses (SIL Open Font License).\n   Generated by cloudflare/fonts.php. */\n";
$files = [];
foreach ($stylesheets as $url) {
    $source = fetch($url, true);
    if ($source === '' || !str_contains($source, '@font-face')) fail("could not download the stylesheet: $url");
    // each block is "/* subset */ @font-face { ... }"
    preg_match_all('#/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})#', $source, $blocks, PREG_SET_ORDER);
    if (!$blocks) {                                   // the "text=" subset has no subset comments
        preg_match_all('#()(@font-face\s*\{[^}]*\})#', $source, $blocks, PREG_SET_ORDER);
    }
    foreach ($blocks as [, $subset, $block]) {
        if ($subset !== '' && !in_array($subset, $keepSubsets, true)) continue;
        if (!preg_match("#url\((https://[^)]+)\)\s*format\('woff2'\)#", $block, $u)) fail('no woff2 url in a font block');
        preg_match("#font-family:\s*'([^']+)'#", $block, $family);
        preg_match('#font-weight:\s*([^;]+);#', $block, $weight);
        $name = strtolower(preg_replace('/\W+/', '-', $family[1])) . '-' . ($subset ?: 'subset') . '-' . str_replace(' ', '-', trim($weight[1])) . '.woff2';
        if (!isset($files[$u[1]])) {                  // variable fonts: one file serves several weights
            $data = fetch($u[1]);
            if (strlen($data) < 1000) fail("could not download {$u[1]}");
            file_put_contents("$dir/$name", $data);
            $files[$u[1]] = $name;
        }
        $css .= str_replace($u[1], $files[$u[1]], preg_replace('#\s*\n\s*#', ' ', $block)) . "\n";
    }
}
file_put_contents("$dir/fonts.css", $css);
$total = array_sum(array_map('filesize', glob("$dir/*.woff2")));
echo 'Saved ' . count(glob("$dir/*.woff2")) . ' font files (' . round($total / 1024) . " KB) and fonts.css to cloudflare/fonts/\n";
foreach (glob("$dir/*.woff2") as $f) printf("  %-44s %6.1f KB\n", basename($f), filesize($f) / 1024);
